# Generated by Django 4.1.2 on 2022-10-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
