# Generated by Django 4.1.2 on 2022-10-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_details_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
