# Generated by Django 4.1.2 on 2022-10-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
