# Generated by Django 4.1.2 on 2022-11-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldcart',
            name='total',
            field=models.IntegerField(default=1),
        ),
    ]
