# Generated by Django 4.1.2 on 2022-11-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_details_dis_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_offer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product_details',
            name='pro_offer',
            field=models.IntegerField(null=True),
        ),
    ]
