# Generated by Django 4.1.2 on 2022-11-11 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_cat_offer_product_details_pro_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_offer',
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='pro_offer',
        ),
        migrations.CreateModel(
            name='product_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('offer', models.IntegerField()),
                ('offer_type', models.CharField(default='Product', max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product_details')),
            ],
        ),
        migrations.CreateModel(
            name='cat_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('offer', models.IntegerField()),
                ('offer_type', models.CharField(default='Category', max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
