# Generated by Django 4.1.2 on 2022-11-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_category_cat_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='p_offer',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cat_offer',
            name='offer',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product_offer',
            name='offer',
            field=models.FloatField(),
        ),
    ]
