# Generated by Django 4.1.2 on 2022-11-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_details_p_offer_alter_cat_offer_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat_offer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product_offer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
