# Generated by Django 4.1.2 on 2022-11-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_offer_up_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_offer',
            name='up_to',
            field=models.FloatField(default=0),
        ),
    ]
