# Generated by Django 4.1.2 on 2022-11-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_offer_up_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_offer',
            name='up_to',
        ),
        migrations.AddField(
            model_name='cat_offer',
            name='up_to',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
