# Generated by Django 4.1.2 on 2022-11-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='code',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
